-- MySQL Script generated by MySQL Workbench
-- 07/19/15 13:18:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pelicula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`pelicula` (
  `pelicula_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(20) NOT NULL COMMENT '',
  `categoria` VARCHAR(45) NULL COMMENT '',
  `descripcion` MEDIUMTEXT NULL COMMENT '',
  `formato` VARCHAR(45) NOT NULL COMMENT '',
  `status` VARCHAR(15) NULL COMMENT '',
  `fecha_renta` DATE NULL COMMENT '',
  `fecha_devolucion` DATE NULL COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `clinete_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `codigo` VARCHAR(45) NOT NULL COMMENT '',
  `numero_id` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(45) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`clinete_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cargo` VARCHAR(45) NOT NULL COMMENT '',
  `cliente_clinete_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_id`)  COMMENT '',
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`cliente_clinete_id`)
    REFERENCES `mydb`.`cliente` (`clinete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_cliente_idx` ON `mydb`.`usuario` (`cliente_clinete_id` ASC)  COMMENT '';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
